# app-stack.yml
version: '3.8'

services:
  flight-app:
    image: srinu1816/flightservices:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-stack_mysql-db:3306/flightdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: "8080"
    networks:
      - db-stack_db-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  db-stack_db-network:
    external: true
