# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  root-password: {{ .Values.database.rootPassword | b64enc }}
